### ISSUE TITLE
Incorrect channel for `is_dead` checking?

### ISSUE THREAD

**Issue by dwoiwode** [SethPipho/pytorch-neural-cellular-automata#1]
Hi, I am currently using your repository to get an understanding of implementations of NCA and it is very helpful in doing so.
There is one issue that I am currently not quite sure if it is a mistake in my understanding or a bug in your code:

In [train.py, Line 64](https://github.com/SethPipho/pytorch-neural-cellular-automata/blob/bbe44c603a5693dbe68059272c1a63114d207572/pytorch_neural_ca/train.py#L64):
```python
is_dead = torch.amax(state[:,4,:,:]) < .1
```

I guess you want to check whether the alpha-channel is below a threshold (same threshold as in alive-masking?). Therefore you want to take the channel with index 3, right?

**Comment by SethPipho** [comment]
Yes, that is a bug on my part. Good catch. Should be fixed now.
